[package]
authors = ["Jiangqiu Shen"]
description = "A simple PIM"
edition = "2021"
license = "MIT"
name = "spmspm_pim"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.0.15", features = ["derive", "color"]}
clap_complete = "4.0.2"
enum-as-inner = "0.5.1"
serde = {version = "1.0.145", features = ["derive"]}
serde_json = "1.0.86"
sprs = {git = "https://github.com/sparsemat/sprs.git", branch = "master"}
toml = "0.5.9"
tracing = "0.1.37"
tracing-subscriber = {version = "0.3.16", features = ["env-filter"]}
[profile.release]
lto = true
opt-level = 3

