activate_cycle = 2
columns = 256
dram_type = 'DDR4'
graph_path = 'mtx/outerspace/amazon0312/amazon0312.mtx'
output_path = 'output/ddr4.json'
precharge_cycle = 2
row_size = 2
rows = 32768
subarray_provider_size = 2
subarray_task_queue_size = 2
subarrays = 16

[channels]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 16
num = 1

[ranks]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 12
num = 2

[chips]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 8
num = 8

[bank_groups]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 8
num = 8

[banks]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 8
num = 8
