activate_cycle = 22
cas = 22
columns = 256
dram_type = 'DDR4'
precharge_cycle = 22
rows = 32768
subarray_provider_size = 2
subarray_task_queue_size = 2
subarrays = 32
window_size = 0

graph_path = [
  "mtx/outerspace/2cubes_sphere/2cubes_sphere.mtx",
]

output_path = 'output/gearbox_out.json'

[channels]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 16
num = 32

[ranks]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 12
num = 1

[chips]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 8
num = 1

[bank_groups]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 8
num = 1

[banks]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 8
num = 64

[gearbox_config]
layers = 8
stacks = 4
topk = 0.0001
