
activate_cycle = 22
cas = 22
columns = 256
dram_type = 'DDR4'
graph_path = [
  "mtx/gearbox/ca-hollywood-2009.mtx",
  "mtx/gearbox/soc-orkut.mtx",
  "mtx/gearbox/soc-twitter-2010.mtx",
  "mtx/gearbox/road_usa.mtx",
  "mtx/gearbox/cit-Patents.mtx",
]
output_path = 'output/gearbox_g.json'
precharge_cycle = 22
rows = 32768
subarray_provider_size = 2
subarray_task_queue_size = 2
subarrays = 32
window_size = 0

[channels]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 16
num = 32

[ranks]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 12
num = 1

[chips]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 8
num = 1

[bank_groups]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 8
num = 1

[banks]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 8
num = 64

[gearbox_config]
layers = 8
stacks = 4
topk = 0.0005
