
activate_cycle = 22
analysis = "RealJump"
cas = 22
columns = 256
dram_type = 'DDR4'
graph_path = [
  "mtx/gearbox/ca-hollywood-2009.mtx",
  "mtx/outerspace/2cubes_sphere/2cubes_sphere.mtx",
  "mtx/outerspace/filter3D/filter3D_E.mtx",
  "mtx/outerspace/cage12/cage12.mtx",
  "mtx/outerspace/filter3D/filter3D.mtx",
  "mtx/outerspace/scircuit/scircuit.mtx",
  "mtx/outerspace/mario002/mario002.mtx",
  "mtx/outerspace/offshore/offshore.mtx",
]
# mapping = "SameSubarray"
mapping = "SameBank"
# mapping = "SameBankWeightedMapping"
output_path = 'output/gearbox_out_v2_all.json'

precharge_cycle = 22
remap_cycle = 3
remap_gap = 16
rows = 512
subarray_provider_size = 2
subarray_task_queue_size = 2
subarrays = 32
window_size = 0
[channels]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 16
num = 8

[ranks]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 12
num = 1

[chips]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 8
num = 1

[bank_groups]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 8
num = 1

[banks]
max_msg_generated = 2
max_msg_in = 2
max_msg_out = 2
merger_num = 8
num = 64

[gearbox_config]
batch = [1, 2, 4, 8, 16]
layers = 8
stacks = 4
topk = [0.0005]
