name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest
    steps:  
    - name: Install Rust
      run: rustup update stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
